-- Users table seeds here (Example)
INSERT INTO pin_icons (category_name, icon_url) VALUES ('Dining','http://maps.google.com/mapfiles/ms/micons/restaurant.png');
INSERT INTO pin_icons (category_name, icon_url) VALUES ('Entertainment','http://maps.google.com/mapfiles/ms/micons/movies.png');
INSERT INTO pin_icons (category_name, icon_url) VALUES ('Cafe','http://maps.google.com/mapfiles/ms/micons/coffeehouse.png');

/* List of Google Icons
    http://maps.google.com/mapfiles/ms/icons/POI.png
    http://maps.google.com/mapfiles/ms/icons/POI.shadow.png
    http://maps.google.com/mapfiles/ms/icons/arts.png
    http://maps.google.com/mapfiles/ms/icons/arts.shadow.png
    http://maps.google.com/mapfiles/ms/icons/bar.png
    http://maps.google.com/mapfiles/ms/icons/bar.shadow.png
    http://maps.google.com/mapfiles/ms/icons/blue-dot.png
    http://maps.google.com/mapfiles/ms/icons/blue-pushpin.png
    http://maps.google.com/mapfiles/ms/icons/blue.png
    http://maps.google.com/mapfiles/ms/icons/bus.png
    http://maps.google.com/mapfiles/ms/icons/bus.shadow.png
    http://maps.google.com/mapfiles/ms/icons/cabs.png
    http://maps.google.com/mapfiles/ms/icons/cabs.shadow.png
    http://maps.google.com/mapfiles/ms/icons/camera.png
    http://maps.google.com/mapfiles/ms/icons/camera.shadow.png
    http://maps.google.com/mapfiles/ms/icons/campfire.png
    http://maps.google.com/mapfiles/ms/icons/campfire.shadow.png
    http://maps.google.com/mapfiles/ms/icons/campground.png
    http://maps.google.com/mapfiles/ms/icons/campground.shadow.png
    http://maps.google.com/mapfiles/ms/icons/caution.png
    http://maps.google.com/mapfiles/ms/icons/caution.shadow.png
    http://maps.google.com/mapfiles/ms/icons/coffeehouse.png
    http://maps.google.com/mapfiles/ms/icons/coffeehouse.shadow.png
    http://maps.google.com/mapfiles/ms/icons/convienancestore.png
    http://maps.google.com/mapfiles/ms/icons/convienancestore.shadow.png
    http://maps.google.com/mapfiles/ms/icons/cycling.png
    http://maps.google.com/mapfiles/ms/icons/cycling.shadow.png
    http://maps.google.com/mapfiles/ms/icons/dollar.png
    http://maps.google.com/mapfiles/ms/icons/dollar.shadow.png
    http://maps.google.com/mapfiles/ms/icons/drinking_water.png
    http://maps.google.com/mapfiles/ms/icons/drinking_water.shadow.png
    http://maps.google.com/mapfiles/ms/icons/earthquake.png
    http://maps.google.com/mapfiles/ms/icons/earthquake.shadow.png
    http://maps.google.com/mapfiles/ms/icons/electronics.png
    http://maps.google.com/mapfiles/ms/icons/electronics.shadow.png
    http://maps.google.com/mapfiles/ms/icons/euro.png
    http://maps.google.com/mapfiles/ms/icons/euro.shadow.png
    http://maps.google.com/mapfiles/ms/icons/fallingrocks.png
    http://maps.google.com/mapfiles/ms/icons/fallingrocks.shadow.png
    http://maps.google.com/mapfiles/ms/icons/ferry.png
    http://maps.google.com/mapfiles/ms/icons/ferry.shadow.png
    http://maps.google.com/mapfiles/ms/icons/firedept.png
    http://maps.google.com/mapfiles/ms/icons/firedept.shadow.png
    http://maps.google.com/mapfiles/ms/icons/fishing.png
    http://maps.google.com/mapfiles/ms/icons/fishing.shadow.png
    http://maps.google.com/mapfiles/ms/icons/flag.png
    http://maps.google.com/mapfiles/ms/icons/flag.shadow.png
    http://maps.google.com/mapfiles/ms/icons/gas.png
    http://maps.google.com/mapfiles/ms/icons/gas.shadow.png
    http://maps.google.com/mapfiles/ms/icons/golfer.png
    http://maps.google.com/mapfiles/ms/icons/golfer.shadow.png
    http://maps.google.com/mapfiles/ms/icons/green-dot.png
    http://maps.google.com/mapfiles/ms/icons/green.png
    http://maps.google.com/mapfiles/ms/icons/grn-pushpin.png
    http://maps.google.com/mapfiles/ms/icons/grocerystore.png
    http://maps.google.com/mapfiles/ms/icons/grocerystore.shadow.png
    http://maps.google.com/mapfiles/ms/icons/groecerystore.png
    http://maps.google.com/mapfiles/ms/icons/groecerystore.shadow.png
    http://maps.google.com/mapfiles/ms/icons/helicopter.png
    http://maps.google.com/mapfiles/ms/icons/helicopter.shadow.png
    http://maps.google.com/mapfiles/ms/icons/hiker.png
    http://maps.google.com/mapfiles/ms/icons/hiker.shadow.png
    http://maps.google.com/mapfiles/ms/icons/homegardenbusiness.png
    http://maps.google.com/mapfiles/ms/icons/homegardenbusiness.shadow.png
    http://maps.google.com/mapfiles/ms/icons/horsebackriding.png
    http://maps.google.com/mapfiles/ms/icons/horsebackriding.shadow.png
    http://maps.google.com/mapfiles/ms/icons/hospitals.png
    http://maps.google.com/mapfiles/ms/icons/hospitals.shadow.png
    http://maps.google.com/mapfiles/ms/icons/hotsprings.png
    http://maps.google.com/mapfiles/ms/icons/hotsprings.shadow.png
    http://maps.google.com/mapfiles/ms/icons/info.png
    http://maps.google.com/mapfiles/ms/icons/info.shadow.png
    http://maps.google.com/mapfiles/ms/icons/info_circle.png
    http://maps.google.com/mapfiles/ms/icons/info_circle.shadow.png
    http://maps.google.com/mapfiles/ms/icons/landmarks-jp.png
    http://maps.google.com/mapfiles/ms/icons/landmarks-jp.shadow.png
    http://maps.google.com/mapfiles/ms/icons/lightblue.png
    http://maps.google.com/mapfiles/ms/icons/lodging.png
    http://maps.google.com/mapfiles/ms/icons/lodging.shadow.png
    http://maps.google.com/mapfiles/ms/icons/ltblu-pushpin.png
    http://maps.google.com/mapfiles/ms/icons/ltblue-dot.png
    http://maps.google.com/mapfiles/ms/icons/man.png
    http://maps.google.com/mapfiles/ms/icons/man.shadow.png
    http://maps.google.com/mapfiles/ms/icons/marina.png
    http://maps.google.com/mapfiles/ms/icons/marina.shadow.png
    http://maps.google.com/mapfiles/ms/icons/mechanic.png
    http://maps.google.com/mapfiles/ms/icons/mechanic.shadow.png
    http://maps.google.com/mapfiles/ms/icons/motorcycling.png
    http://maps.google.com/mapfiles/ms/icons/motorcycling.shadow.png
    http://maps.google.com/mapfiles/ms/icons/movies.png
    http://maps.google.com/mapfiles/ms/icons/movies.shadow.png
    http://maps.google.com/mapfiles/ms/icons/msmarker.shadow.png
    http://maps.google.com/mapfiles/ms/icons/orange-dot.png
    http://maps.google.com/mapfiles/ms/icons/orange.png
    http://maps.google.com/mapfiles/ms/icons/parkinglot.png
    http://maps.google.com/mapfiles/ms/icons/parkinglot.shadow.png
    http://maps.google.com/mapfiles/ms/icons/partly_cloudy.png
    http://maps.google.com/mapfiles/ms/icons/partly_cloudy.shadow.png
    http://maps.google.com/mapfiles/ms/icons/pharmacy-us.png
    http://maps.google.com/mapfiles/ms/icons/pharmacy-us.shadow.png
    http://maps.google.com/mapfiles/ms/icons/phone.png
    http://maps.google.com/mapfiles/ms/icons/phone.shadow.png
    http://maps.google.com/mapfiles/ms/icons/picnic.png
    http://maps.google.com/mapfiles/ms/icons/picnic.shadow.png
    http://maps.google.com/mapfiles/ms/icons/pink-dot.png
    http://maps.google.com/mapfiles/ms/icons/pink-pushpin.png
    http://maps.google.com/mapfiles/ms/icons/pink.png
    http://maps.google.com/mapfiles/ms/icons/plane.png
    http://maps.google.com/mapfiles/ms/icons/plane.shadow.png
    http://maps.google.com/mapfiles/ms/icons/police.png
    http://maps.google.com/mapfiles/ms/icons/police.shadow.png
    http://maps.google.com/mapfiles/ms/icons/postoffice-jp.png
    http://maps.google.com/mapfiles/ms/icons/postoffice-jp.shadow.png
    http://maps.google.com/mapfiles/ms/icons/postoffice-us.png
    http://maps.google.com/mapfiles/ms/icons/postoffice-us.shadow.png
    http://maps.google.com/mapfiles/ms/icons/purple-dot.png
    http://maps.google.com/mapfiles/ms/icons/purple-pushpin.png
    http://maps.google.com/mapfiles/ms/icons/purple.png
    http://maps.google.com/mapfiles/ms/icons/pushpin_shadow.png
    http://maps.google.com/mapfiles/ms/icons/question.png
    http://maps.google.com/mapfiles/ms/icons/question.shadow.png
    http://maps.google.com/mapfiles/ms/icons/rail.png
    http://maps.google.com/mapfiles/ms/icons/rail.shadow.png
    http://maps.google.com/mapfiles/ms/icons/rainy.png
    http://maps.google.com/mapfiles/ms/icons/rainy.shadow.png
    http://maps.google.com/mapfiles/ms/icons/rangerstation.png
    http://maps.google.com/mapfiles/ms/icons/rangerstation.shadow.png
    http://maps.google.com/mapfiles/ms/icons/realestate.png
    http://maps.google.com/mapfiles/ms/icons/realestate.shadow.png
    http://maps.google.com/mapfiles/ms/icons/recycle.png
    http://maps.google.com/mapfiles/ms/icons/recycle.shadow.png
    http://maps.google.com/mapfiles/ms/icons/red-dot.png
    http://maps.google.com/mapfiles/ms/icons/red-pushpin.png
    http://maps.google.com/mapfiles/ms/icons/red.png
    http://maps.google.com/mapfiles/ms/icons/restaurant.png
    http://maps.google.com/mapfiles/ms/icons/restaurant.shadow.png
    http://maps.google.com/mapfiles/ms/icons/sailing.png
    http://maps.google.com/mapfiles/ms/icons/sailing.shadow.png
    http://maps.google.com/mapfiles/ms/icons/salon.png
    http://maps.google.com/mapfiles/ms/icons/salon.shadow.png
    http://maps.google.com/mapfiles/ms/icons/shopping.png
    http://maps.google.com/mapfiles/ms/icons/shopping.shadow.png
    http://maps.google.com/mapfiles/ms/icons/ski.png
    http://maps.google.com/mapfiles/ms/icons/ski.shadow.png
    http://maps.google.com/mapfiles/ms/icons/snack_bar.png
    http://maps.google.com/mapfiles/ms/icons/snack_bar.shadow.png
    http://maps.google.com/mapfiles/ms/icons/snowflake_simple.png
    http://maps.google.com/mapfiles/ms/icons/snowflake_simple.shadow.png
    http://maps.google.com/mapfiles/ms/icons/sportvenue.png
    http://maps.google.com/mapfiles/ms/icons/sportvenue.shadow.png
    http://maps.google.com/mapfiles/ms/icons/subway.png
    http://maps.google.com/mapfiles/ms/icons/subway.shadow.png
    http://maps.google.com/mapfiles/ms/icons/sunny.png
    http://maps.google.com/mapfiles/ms/icons/sunny.shadow.png
    http://maps.google.com/mapfiles/ms/icons/swimming.png
    http://maps.google.com/mapfiles/ms/icons/swimming.shadow.png
    http://maps.google.com/mapfiles/ms/icons/toilets.png
    http://maps.google.com/mapfiles/ms/icons/toilets.shadow.png
    http://maps.google.com/mapfiles/ms/icons/trail.png
    http://maps.google.com/mapfiles/ms/icons/trail.shadow.png
    http://maps.google.com/mapfiles/ms/icons/tram.png
    http://maps.google.com/mapfiles/ms/icons/tram.shadow.png
    http://maps.google.com/mapfiles/ms/icons/tree.png
    http://maps.google.com/mapfiles/ms/icons/tree.shadow.png
    http://maps.google.com/mapfiles/ms/icons/truck.png
    http://maps.google.com/mapfiles/ms/icons/truck.shadow.png
    http://maps.google.com/mapfiles/ms/icons/volcano.png
    http://maps.google.com/mapfiles/ms/icons/volcano.shadow.png
    http://maps.google.com/mapfiles/ms/icons/water.png
    http://maps.google.com/mapfiles/ms/icons/water.shadow.png
    http://maps.google.com/mapfiles/ms/icons/waterfalls.png
    http://maps.google.com/mapfiles/ms/icons/waterfalls.shadow.png
    http://maps.google.com/mapfiles/ms/icons/webcam.png
    http://maps.google.com/mapfiles/ms/icons/webcam.shadow.png
    http://maps.google.com/mapfiles/ms/icons/wheel_chair_accessible.png
    http://maps.google.com/mapfiles/ms/icons/wheel_chair_accessible.shadow.png
    http://maps.google.com/mapfiles/ms/icons/woman.png
    http://maps.google.com/mapfiles/ms/icons/woman.shadow.png
    http://maps.google.com/mapfiles/ms/icons/yellow-dot.png
    http://maps.google.com/mapfiles/ms/icons/yellow.png
    http://maps.google.com/mapfiles/ms/icons/yen.png
    http://maps.google.com/mapfiles/ms/icons/yen.shadow.png
    http://maps.google.com/mapfiles/ms/icons/ylw-pushpin.png
*/